
version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 767397952451.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t demo-cicd-app .
      - docker tag demo-cicd-app:latest 767397952451.dkr.ecr.ap-south-1.amazonaws.com/demo-cicd-repo:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 767397952451.dkr.ecr.ap-south-1.amazonaws.com/demo-cicd-repo:latest

      - echo Deploying updated image to ECS service...
      - aws ecs update-service \
          --cluster demo-cluster \
          --service demo-task1-service-ssb3sojp \
          --force-new-deployment